gnbId: 1
tac: 1
nci: '0000000100'

host: 127.0.0.1
gtpPort: 2152

plmn:
  mcc: 208
  mnc: 93

amfConfigs:
  - host: 127.0.0.1
    port: 38412

nssais:
  - sst: '0x01'
    sd: '0x010203'

ignoreStreamIds: true