# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
supi: 'imsi-@IMSI@'
# Mobile Country Code value of HPLMN
mcc: '@MCC@'
# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: '@MNC@'

# Permanent subscription key
key: '@KEY@'
# Operator code (OP or OPC) of the UE
op: '@OP@'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: '@OP_TYPE@'
# Authentication Management Field (AMF) value
amf: '@AMF_VALUE@'
# IMEI number of the device. It is used if no SUPI is provided
imei: '@IMEI@'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '@IMEI_SV@'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - @GNB_IP_ADDRESS@

# UAC Access Identities Configuration
uacAic:
  mps: false
  mcs: false

# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# Initial PDU sessions to be established
sessions:
  - type: '@PDU_TYPE@'
    apn: '@APN@'
    slice:
      sst: @SST@
      sd: @SD@

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: @SST_C@
    sd: @SD_C@

# Default Configured NSSAI for this UE
default-nssai:
  - sst: @SST_D@
    sd: @SD_D@

# Supported integrity algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true

# Supported encryption algorithms by this UE
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'
