gnbId: 1
tac: 1
nci: '000000000000000000000000000000000001'

gnbPlmn:
  mcc: 286
  mnc: 1

amfConfigs:
  - guami:
      mcc: 286
      mnc: 1
      amfRegionId:
        hex: '2a'
      amfSetId:
        hex: '5580'
      amfPointer:
        hex: 'a8'
    host: 127.0.0.1
    port: 38412
    isMocked: false
    mockingFile: mockedAmf.yaml

supportedTAs:
  - tac:
      hex: '000001'
    broadcastPlmns:
      - plmn:
          mcc: 286
          mnc: 1
        taiSliceSupportNssais:
          - sst:
              value: 1
            sd:
              value:
                hex: '010203'

ignoreStreamIds: false