snn: '5G:mnc093.mcc286.3gppnetwork.org'
key: '465b5ce8b199b49faa5f0a2ee238a001'
op: 'cdc202d5123e20f62b6d676ac72cb318'
amf: '8000'
imei: '356938035643809'
supi: 'imsi-286010000000001'

smsOverNasSupported: false
dnn: 'internet'

requestedNssai:
  - sst:
      value: 1
    sd:
      hex: '010203'

userLocationInformationNr:
  nrCgi:
    plmn:
      mcc: 286
      mnc: 1
    nrCellIdentity:
      hex: '01b2c3d4e0'
  tai:
    mcc: 286
    mnc: 1
    tac: '000001'

