mcc: '208'          # Mobile Country Code value
mnc: '01'           # Mobile Network Code value (2 or 3 digits)

nci: '0x0000000d0'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 89             # Tracking Area Code

linkIp: 10.194.124.10   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 10.194.124.10   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 10.194.124.10    # gNB's local IP address for N3 Interface (Usually same with local IP)

# List of AMF address information
amfConfigs:
  - address: 172.19.10.172
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1
    sd: 0x000001

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true
