test-cases:

  initial-registration:
    - "@cmd": INITIAL_REGISTRATION
      followOn: FOR_PENDING    # Possible values: NO_FOR_PENDING, FOR_PENDING

  periodic-registration:
    - "@cmd": INITIAL_REGISTRATION
      followOn: NO_FOR_PENDING

    - "@cmd": SLEEP
      duration: 60

    - "@cmd": PERIODIC_REGISTRATION
      followOn: NO_FOR_PENDING

  de-registration:
    - "@cmd": INITIAL_REGISTRATION
      followOn: FOR_PENDING

    - "@cmd": SLEEP
      duration: 5

    - "@cmd": DEREGISTRATION
      isSwitchOff: false

  pdu-session-establishment:
    - "@cmd": INITIAL_REGISTRATION
      followOn: FOR_PENDING

    - "@cmd": SLEEP
      duration: 15

    - "@cmd": PDU_SESSION_ESTABLISHMENT

load-testing:
  number-of-UE: 1