snn: '5G:mnc001.mcc001.3gppnetwork.org'
key: '465b5ce8b199b49faa5f0a2ee238a001'
op: 'cdc202d5123e20f62b6d676ac72cb318'
amf: '8000'
imei: '356938035643809'
supi: 'imsi-001001000000001'

smsOverNasSupported: true
dnn: 'internet'

requestedNssai:
  - sst:
      value: 1
#    sd:
#      hex: 09afaf

userLocationInformationNr:
  nrCgi:
    plmn:
      mcc: 1
      mnc: 1
    nrCellIdentity:
      hex: '01b2c3d4e0'
  tai:
    mcc: 1
    mnc: 1
    tac: '000075'
  timeStamp:
    hex: 5b5fa680