amf.host: 10.154.14.5
amf.port: 38419
amf.mocked: true
amf.mockedRemote: mockedRemote.yaml

input.NgSetupFlow: flows/ngsetup.yaml
input.RegistrationFlow: flows/registration.yaml
input.PeriodicRegistrationFlow: flows/registration.yaml
input.PduSessionEstablishmentFlow: flows/pduSessionEstablishment.yaml
input.PduSessionReleaseFlow: flows/pduSessionRelease.yaml
input.UEContextReleaseRequestFlow: flows/ueContextReleaseRequest.yaml
input.ServiceRequestFlow: flows/serviceRequest.yaml
input.DeregistrationFlow: flows/deregistration.yaml
input.NgResetFlow: flows/ngreset.yaml

ueData: '@ueData_i2i.yaml'

ue.smsOverNas: true
ue.requestedNssai:
  - sst:
      value: 1
    sd:
      hex: 09afaf
ue.userLocationInformationNr:
  nrCgi:
    plmn:
      mcc: 1
      mnc: 1
    nrCellIdentity:
      hex: '01b2c3d4e0'
  tai:
    mcc: 1
    mnc: 1
    tac: '000075'
  timeStamp:
    hex: 5b5fa680

context.ranUeNgapId: 1000
